apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-fbc-multiple-components-412
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-fbc-multiple-components-412
    app.kubernetes.io/part-of: e2e-fbc-application
  name: e2e-fbc-multiple-components-412
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: e2e-fbc-multiple-components-412
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: e2e-fbc-multiple-components-412
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/dev-release-team-tenant/e2e-fbc-application/e2e-fbc-multiple-components-412@sha256:000d4d852b26853c7862033b10156367eb16a18ade1abb0cd864d34c81eabcce
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
