apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-fbc-multiple-components-413
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-fbc-multiple-components-413
    app.kubernetes.io/part-of: e2e-fbc-application
  name: e2e-fbc-multiple-components-413
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: e2e-fbc-multiple-components-413
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: e2e-fbc-multiple-components-413
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/dev-release-team-tenant/e2e-fbc-application/e2e-fbc-multiple-components-413@sha256:f675f8fbc11ebdf5ce3f02e8a7c88ecb504803ba7bd91526eed896c7ab608473
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
