apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-fbc-multiple-components-414
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-fbc-multiple-components-414
    app.kubernetes.io/part-of: e2e-fbc-application
  name: e2e-fbc-multiple-components-414
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: e2e-fbc-multiple-components-414
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: e2e-fbc-multiple-components-414
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/dev-release-team-tenant/e2e-fbc-application/e2e-fbc-multiple-components-414@sha256:9cc76b1be0cb81ad5d5f0ea8f37c562610a17d7d01de0aa6e224a08870c06435
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
